// Action types
export const REQUEST_SWELL_INITIATION = 'REQUEST_SWELL_INITIATION';
export const RECEIVE_SWELL_INITIATED = 'RECEIVE_SWELL_INITIATED';
export const ERROR_SWELL_INITIATED = 'ERROR_SWELL_INITIATED';
export const REQUEST_SWELL_IDENTIFY_CUSTOMER = 'REQUEST_SWELL_IDENTIFY_CUSTOMER';
export const RECEIVE_SWELL_IDENTIFY_CUSTOMER = 'RECEIVE_SWELL_IDENTIFY_CUSTOMER';
export const ERROR_SWELL_IDENTIFY_CUSTOMER = 'ERROR_SWELL_IDENTIFY_CUSTOMER';

// Swell SDK Strings
export const SWELL_INITIALIZED = 'swell:initialized';
export const SWELL_SETUP = 'swell:setup';
